### ISSUE TITLE
Read count is not integer after STAR alignment

### ISSUE THREAD

**Issue by huangwb8** [ConYel/spar_pipeline#3]
In the SPAR result, Read count is not integer after `STAR` alignment, but integer for `hisat2`.
Is it normal?

**Comment by ConYel** [comment]
In SPAR results there is expression value which is not an integer number because it is a value extracted from the reads that are inside the peak.
[Here ](https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/nar/46/W1/10.1093_nar_gky330/1/gky330_supplemental_files.pdf?Expires=1581514430&Signature=5NXufPYez2Bx1k5~4dn4IJcfIbwzzQoGWyc~Ku8I3MICV1J5CfLMpBSI6KiMBIvSzk0qdJYKMLVVDb3VAJnx9OqQdko2rQ1gria17fNLv7wQsSGcIUcFa9pnZcBzK-FSYVx8fzS3Rfe9bUGUSkPQSEWng9ChkV7EB~Z~W3hLcsCLjL2Fe4~xfHDoV3iMXZXlEWVS6CcWv9N0XWqb3kW7O9IB2sTBf15lSssu-qOAMJHb17lK4pDx53C0jx2BFJJeMsJctAdzG-YMntZQ3xGTm-hsHYniKC8ABq-PPWVgTSjaNqLjaekzwGM2P7xBKNBjX8LBuTzqhHwRWrw5f0QGcA__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA)it explains how they calculate it.
